project:
  type: website

website:
  title: "breakfastconf"
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- about.qmd
      - href: blog/index.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/machow/breakfastconf-web
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/company/breakfast-conf
        aria-label: LinkedIn

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



